In [1]:
from tensorflow.keras.preprocessing.text import one_hot

c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\cg-dte\appdata\local\programs\python\python37\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8475, 6120, 8858, 418], [8475, 6120, 8858, 7665], [8475, 5277, 8858, 1127], [1583, 878, 2767, 903, 9411], [1583, 878, 2767, 903, 4970], [7077, 8475, 7575, 8858, 7174], [2074, 5288, 7709, 903]]


In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8475 6120 8858  418]
 [   0    0    0    0 8475 6120 8858 7665]
 [   0    0    0    0 8475 5277 8858 1127]
 [   0    0    0 1583  878 2767  903 9411]
 [   0    0    0 1583  878 2767  903 4970]
 [   0    0    0 7077 8475 7575 8858 7174]
 [   0    0    0    0 2074 5288 7709  903]]


In [7]:
dim=10

In [8]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [10]:
print(model.predict(embedded_docs))

[[[ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
   -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
    1.12364441e-03 -1.69739611e-02]
  [ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
   -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
    1.12364441e-03 -1.69739611e-02]
  [ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
   -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
    1.12364441e-03 -1.69739611e-02]
  [ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
   -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
    1.12364441e-03 -1.69739611e-02]
  [ 1.36969723e-02  1.91824771e-02  2.18301527e-02 -1.24704093e-04
   -1.61513574e-02  1.30694248e-02 -6.23613596e-06 -4.63936701e-02
    4.07238863e-02 -1.38282180e-02]
  [-3.69525440e-02 -1.12266541e-02 -3.97887081e-03  1.03544444e-04
   -3.57141346e-03 -4.21513915e-02 -4.66466211e-02 -3.58863957e-02
    3.85702513e-

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 8475, 6120, 8858,  418])

In [12]:
print(model.predict(embedded_docs)[0])

[[ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
  -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
   1.12364441e-03 -1.69739611e-02]
 [ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
  -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
   1.12364441e-03 -1.69739611e-02]
 [ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
  -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
   1.12364441e-03 -1.69739611e-02]
 [ 4.63311560e-02 -4.33482043e-02 -3.77516747e-02  2.37567313e-02
  -1.83971748e-02  1.79404728e-02  3.90033610e-02 -3.41548696e-02
   1.12364441e-03 -1.69739611e-02]
 [ 1.36969723e-02  1.91824771e-02  2.18301527e-02 -1.24704093e-04
  -1.61513574e-02  1.30694248e-02 -6.23613596e-06 -4.63936701e-02
   4.07238863e-02 -1.38282180e-02]
 [-3.69525440e-02 -1.12266541e-02 -3.97887081e-03  1.03544444e-04
  -3.57141346e-03 -4.21513915e-02 -4.66466211e-02 -3.58863957e-02
   3.85702513e-02  2.34964006e-02